### ISSUE TITLE
URLs in "i" pop ups

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#104]
If there is a URL in one of the "Subject Metadata" fields and the user clicks it they are taken off the page and lose the current subject. The back button returns to a different subject. I am referencing to the metadata accessible after clicking the ⓘ icon at the bottom of the subject image.  The links can be alt-clicked and "Open in New Tab/Window" used but the transcriber may not know this.

Is there an easy solution to this?

**Comment by mcbouslog** [comment]
There's [a similar issue](https://github.com/zooniverse/Panoptes-Front-End/issues/2962) in the Panoptes-Front-End repo we'll use for project management purposes.

**Comment by mcbouslog** [comment]
closing in this repo, belongs in the PFE repo, covered by [PFE Issue 2962](https://github.com/zooniverse/Panoptes-Front-End/issues/2962)
