### ISSUE TITLE
Change NHM logo

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#108]
change to new logo (attached) in "Collaborating Institutions, Organizations and Funders" and elsewhere on the site as needed.

This is not a priority for the redesign.

![naturalhistorymuseumlogo_black_jpg](https://cloud.githubusercontent.com/assets/2152565/17588312/3b5f016e-5f8b-11e6-90f4-aa2cf477fd80.jpg)

**Comment by mcbouslog** [comment]
#113 Closes
