### ISSUE TITLE
Header will not work in IE 11

### ISSUE THREAD

**Issue by rafelafrance** [zooniverse/notes-from-nature-landing#118]
Note that Edge works fine but not IE 11.

Also the main toe-tag icon appears in the middle of the header.

The header links are visible just not clickable. Maybe this is a z-order issue.

**Comment by robgur** [comment]
I guess people still use IE, so maybe we need to fix this.  Next week?
-r

**Comment by mcbouslog** [comment]
Pull Request #127 closes.
