### ISSUE TITLE
Facebook share option

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#126]
When you share the NFN page directly on Facebook the second line reads "zoo react boilerplate." Can we change it to something else? For example "help unlock important biodiversity data" or "Join us in transcribing museum records that contain important biodiversity data"

**Comment by rafelafrance** [comment]
This isn't in the landing code base. Reassigning.

**Comment by mcbouslog** [comment]
@denslowm - is this issue still applicable? I just tried sharing https://www.notesfromnature.org/ in a Facebook message and I think it appeared as would be desired.

**Comment by denslowm** [comment]
No, it appears to behave as expected now. I tested it and it does share as desired. I believe it can be closed.
