### ISSUE TITLE
review workflow load time

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/notes-from-nature-landing#13]
review workflow load time

**Comment by mcbouslog** [comment]
possible solutions:
- ~~https://github.com/zooniverse/Panoptes/pull/1821~~ - merged, but not sure made much of a difference
- hardcode basic workflow info needed for landing home
- better long-term solution? can we request workflows without tasks from API? <-- f/u post launch

**Comment by parrish** [comment]
Closed by #46
