### ISSUE TITLE
review mobile styling

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/notes-from-nature-landing#14]
review mobile styling

**Comment by rafelafrance** [comment]
I looked at this with an android phone and tablet

For the landing pages themselves:

1) Add padding around the contributor icons. Also have them wrap
2) On the about page fix the width on the top paragraph when things are very thin.
3) Fix reasons section on landing page
4) In general, look at replacing flex-flow: row with flex-direction and flex-wrap in some places

I can handle these but I suspect that there are other issues you may want to work on the data entry side.

I'll create an issue #14 branch

**Comment by rafelafrance** [comment]
I am moving item 2) to it's own issue #18.
