### ISSUE TITLE
Denominator on statistics page

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#143]
On the Statistics page here:
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats?_ga=1.200774441.685869320.1470922371

There seems to be a missing denominators on the two most recent expedition stats. They are Pinned Specimen_Trechine Ground Beetles and Herbarium_Arkansas Dendrology: Part I: Gymnosperms -- 16.

**Comment by mcbouslog** [comment]
status update: back-end devs investigating, I'll check-in with them for updates

**Comment by mcbouslog** [comment]
back-end devs fixed
