### ISSUE TITLE
Arkansas Dendrology: Part 2

### ISSUE THREAD

**Issue by rafelafrance** [zooniverse/notes-from-nature-landing#144]
I have the following expedition ready to go. Can you set it all up and I will activate shortly after?

Here is the information:
Workflow name: Arkansas Dendrology: Part 2: Magnolias, pawpaws, sassafras, and Dutchman's pipe -- 19 September 2016 #2563

Expedition name: Arkansas Dendrology: Part 2: Magnolias, pawpaws, sassafras, and Dutchman's pipe  -- 19 September 2016
Image: Attached
URL: https://biospex.org/project/plants-of-arkansas-discovery-and-dissemination
Hover text:
This is the second in a series of educational focused expeditions being used for @tmarsico’s dendrology course at the Arkansas State University.

Thanks!

![herbarium_arkansas_dendrology_part_2](https://cloud.githubusercontent.com/assets/11902400/18446696/7f17cb3c-78f1-11e6-908d-eb77a7e857f6.jpg)

**Comment by mcbouslog** [comment]
PR #145 closes.
