### ISSUE TITLE
Recent Transcriptions in Field Book not updating 

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#147]
Recent Transcriptions in Field Book not updating (Recent Expeditions appears to be working fine).

https://www.notesfromnature.org/field-book

**Comment by rafelafrance** [comment]
AFAICT: This is an API issue. It's not honoring the sort order parameter. We need to reverse sort the classifications by creation date and it's not happening now.

It will be fixed when we either get better instructions for how to sort records in an API call or the API is fixed.

**Comment by rafelafrance** [comment]
See this [discussion](https://github.com/zooniverse/Panoptes/issues/1993) for a possible solution

**Comment by rafelafrance** [comment]
I'm asking for help here.

The server is returning the correct data but the Panoptes client logic is stripping out the data.

That is, this works and returns an array of recent transcripts:

`https://panoptes-staging.zooniverse.org/api/users/{user_id}/recents?project_id=1613&sort=-created_at&page_size=6`

But the call to

`apiClient.type('users').get('${userId}/recents',  { project_id: config.projectId, sort: '-created_at', page_size: 6 })`

Is losing this returned data

**Comment by eatyourgreens** [comment]
You're trying to retrieve a user with ID '${userId}/recents' with the API client, which will return nothing. What you want to use is `user.get('recents')` where `user` is the logged-in user. See 
https://github.com/zooniverse/diagnosislondon/blob/master/app/profile.cjsx#L35-L38

**Comment by rafelafrance** [comment]
Yup, that worked. Thanks!

**Comment by robgur** [comment]
Thanks, all.

**Comment by rafelafrance** [comment]
Using the recents API I was able to remove a lot of code. A good thing.
