### ISSUE TITLE
90% issue on Statistics page

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#148]
Expeditions are getting stuck at 90% on statistics page. A current expedition (Leaf-cutter bees 1) has been at 90% complete for at least 3 days. 

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats?_ga=1.208573333.685869320.1470922371

It is unclear if it is complete or not. Classifications are 9,010 / 8,997, but Images retired are 2,978 / 2,999.

![image](https://cloud.githubusercontent.com/assets/2152565/18510836/78bdcf3c-7a3d-11e6-8be6-c9da43df27ed.png)

**Comment by robgur** [comment]
Known issue, but the stats being off by that much is a concern.

**Comment by mcbouslog** [comment]
I think changing the completeness calc from based on retirement to based on classifications addresses this, but please reopen if not.
