### ISSUE TITLE
Field Book issue summary

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#149]
I realize that some of these are already known (e.g., #147 ) and don't actually all deal with the Field Book specifically, but I wanted to create an issue here until I have time to split these up.

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/89238?comment=169699&page=1
- (See issue #78) At least some people (including me, using Firefox 47 on Windows 7) can't get there at all because the login link on the NfN main page doesn't log us in. (That login method does work for me using the dreaded / dreadful Internet Explorer. I use the Zooniverse Sign In function that appears in the upper right corner when you select an expedition while not yet logged in. Even if the other login worked for me in Firefox, I prefer the Zooniverse login because it gives me simultaneous access to both sites.)
- (See issue #147) The images shown under "Recent Transcriptions" are not at all recent. They are months old and don't change although I continue to do classifications daily (the ones shown on my Field Book all show 'Transcribed on June 16, 2016' when I hover the mouse over them).
- (Open for discussion) It would be very helpful if our actual most recent few images were shown there and shown in the same way that images are shown in our Collections and Favorites lists, which allows us to view a larger form of the image and, most importantly, to add comments to them.
- (Open for discussion) It would be a nice enhancement if we could see our counts for all expeditions we've classified in. Now we can only see 4.
- (Open for discussion) It would also be a nice enhancement to add a link in the badges column to an 'info about badges' message that lists each of the available badges and what it takes to earn them.

**Comment by mcbouslog** [comment]
Copied to https://github.com/zooniverse/notes-from-nature-field-book/issues/23, closing.
