### ISSUE TITLE
Add Google Analytics to landing page

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#152]
Please add Google Analytics to landing page. 
We should be clear which pages will get tracked. For example if someone shares the direct link to an expedition I don't think this will get tracked. That probably can't be fixed since those links change for every expedition.

**Comment by mcbouslog** [comment]
maybe https://www.npmjs.com/package/react-google-tag-manager

**Comment by mcbouslog** [comment]
I think we've had [Google Tag Management](https://github.com/zooniverse/notes-from-nature-landing/blob/master/webpack.production.config.js#L29) in since launch. I'm following up with Grant to see if it's been working, what level of detail has been tracked, etc., and will report back.

**Comment by mcbouslog** [comment]
good news! it has been working. here's a CSV I just exported, though I know nothing about Google Analytics so I'm not sure how useful this particular file will be. nonetheless, we will be tracking activity.
[Analytics Zooniverse Global Pages 20160918-20161018.xlsx](https://github.com/zooniverse/notes-from-nature-landing/files/539398/Analytics.Zooniverse.Global.Pages.20160918-20161018.xlsx)

**Comment by mcbouslog** [comment]
@denslowm, @rafelafrance - may I close this issue and we'll follow-up on what Google Analytics info you'd like through email or other forms of communication?

**Comment by rafelafrance** [comment]
We should open another issue for further enhancements.
