### ISSUE TITLE
Icons and badges for for Fossils group

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#160]
I think we should call the group "Fossils"

Badges should be added at 1, 10 and 100 transcriptions. 

Please add the following graphics for group icon and badges. 
![paleon1](https://cloud.githubusercontent.com/assets/2152565/19318655/cfe13ba2-9066-11e6-8bda-d728accb0cf1.png)
![paleon2](https://cloud.githubusercontent.com/assets/2152565/19318656/d168643c-9066-11e6-83d4-da35ccfc997c.png)
![paleon3](https://cloud.githubusercontent.com/assets/2152565/19318662/d6add0f8-9066-11e6-8ede-9631fd803d89.png)

OK, .svg (icon) not supported so will have to e-mail that one.

**Comment by robgur** [comment]
The Order of badges is from most covered (1 transcription) to least covered
(100 transcriptions), in case it wasn't totally obvious.

**Comment by telesphore** [comment]
May I please get names for these badges?

**Comment by robgur** [comment]
You mean labels that users see, e.g.
"Junior Preparator" "Senior Preparator" and "Curator"?

or do you mean like a file name that users _don't see_ eg.
 "Trilobite1", "Trilobite10", "Trilobite100"?

**Comment by rafelafrance** [comment]
The first. thanks

**Comment by mcbouslog** [comment]
#162 closed.
