### ISSUE TITLE
Icons and badges for for Aquatics group

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#161]
The new group shall be called "Aquatics"

Badges should be added at 1, 10 and 100 transcriptions. The images should be 1,2,3 in order of emergence. 
Please add the following graphics for badges. I will email the icon since the file type is not supported here.

![wet1](https://cloud.githubusercontent.com/assets/2152565/19367465/92dd908c-9158-11e6-97b1-3c35493953ed.png)
![wet2](https://cloud.githubusercontent.com/assets/2152565/19367469/945b33e2-9158-11e6-80d8-b0968d237099.png)
![wet3](https://cloud.githubusercontent.com/assets/2152565/19367470/95a4f990-9158-11e6-9cc2-ed155fcde303.png)

**Comment by telesphore** [comment]
May I please get some names for these badges?

**Comment by robgur** [comment]
Yep, how about "larval caddisfly", "emerging adult", "adults caddisfly"

**Comment by rafelafrance** [comment]
great thanks!

**Comment by mcbouslog** [comment]
#162 closed.
