### ISSUE TITLE
Numbers jumping around

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#194]
I realize this might be an API issue, but posting it here to start out. 

I have gotten two independent reports of percentage complete values fluctuating up and down. In addition, I am now seeing previously completed expeditions showing back up on the site as live. 

Both users are using 
Windows 8.1 
Chrome Version 54.0.2840.71 m.
Firefox (not version given).

**Comment by denslowm** [comment]
@mcbouslog Any thoughts on this? Still seeming strange behavior today.

**Comment by mcbouslog** [comment]
there indeed may be an issue with our stats backend, but which workflows' percentages were fluctuating and which workflows previously completed have shown back up?

**Comment by denslowm** [comment]
I am not sure I can give you an exhaustive list, but here are a few I know for sure.

Trechine Ground Beetles was definitely finished before I loaded Tiger Beetles 3. Now it shows at 98%

Tiger Beetles is saying 0%, but it was previously at over 5%

Natural North Carolina's Adoxaceae was at almost 9% and is now showing at less than 1%.  

There are bunch of 0% showing up right now that had more previously. 

Overall it seems like values are down.

**Comment by eatyourgreens** [comment]
I think this might be happening because Panoptes is calculating completeness now based on number of retired subjects, rather than classification counts. See this discussion on Talk: https://www.zooniverse.org/talk/14/118004

**Comment by denslowm** [comment]
We are still talking this through, so let's keep this open until all the issues are resolved. 

I have a question in the mean time. Has anyone at the Zooniverse written up anything to explain this to volunteers? This seems critical given that we now have a choice of Classification or Retirement. I seems that we are going to need to communicate this to volunteers and providers regardless of what we choose.

**Comment by mcbouslog** [comment]
The landing page's expedition cards are calculating completeness based on retired subjects, while on the Stats page it's calculating completeness based on classifications.

- [ ] update landing page expedition cards to calculate completeness based on classifications (will need to add `classifications_count,subjects_count`, maybe `retirement` (to get retirement count), to workflow API request (`workflow.classifications_count / (workflow.subjects_count * workflow.retirement.options.count)`)
