### ISSUE TITLE
Dead link on About/Research page

### ISSUE THREAD

**Issue by MobileMaggie** [zooniverse/notes-from-nature-landing#205]
The team info has been updated, so on this page https://www.zooniverse.org/projects/zooniverse/notes-from-nature/about/research the hyperlink on under the word "here" in the final paragraph also needs updating.  

It currently points to https://www.zooniverse.org/projects/zooniverse/notes-from-nature/about/projects/zooniverse/notes-from-nature/about/team but should point to https://www.zooniverse.org/projects/zooniverse/notes-from-nature/about/team

**Comment by rafelafrance** [comment]
Have a look-see now
