### ISSUE TITLE
add Fungi badges

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#225]
We currently have 3 fungi badges that will relate to a new group called Fungi

1. spore
2. mycelium
3. mushroom

@robgur I am thinking that we make these consistent with the insect badges. That is the interval 1, 25 and 100. Do you concur? 

![spore](https://cloud.githubusercontent.com/assets/2152565/24196857/ee036484-0ec4-11e7-82cf-64aedfa680aa.png)
![mycelium](https://cloud.githubusercontent.com/assets/2152565/24196861/f2c28c2a-0ec4-11e7-9c29-a6c9ae6a415b.png)
![mushroom](https://cloud.githubusercontent.com/assets/2152565/24196864/f6a9afc6-0ec4-11e7-880d-0b4c278fc523.png)

**Comment by robgur** [comment]
Yep, concur.
