### ISSUE TITLE
filter completed expeditions to not include workflows in progress

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/notes-from-nature-landing#55]
currently Completed Expeditions include workflows that are being built or recently created that are not yet active (`active: false` and display name not have "Template").

as discussed on Slack, let's add additional criteria to filter expeditions so only actually completed expeditions are included.

ideally this would involve the `finished_at` property, but there's currently a [known issue](https://github.com/zooniverse/Panoptes/issues/1571). until that issue is worked out, I may temporarily filter based on `completeness: 1`, but this is NOT a long-term solution, so please don't close the issue until the filter is properly updated.

**Comment by mcbouslog** [comment]
the known issue noted above has been fixed.
- [ ] confirm fixed
- [ ] retro-actively apply to previously finished workflows? doubtful
- [ ] if doesn't retro-actively apply, can we set manually?

**Comment by rafelafrance** [comment]
You merged this a while back. Closing.
