### ISSUE TITLE
Fix display issues with very long expedition snippets and titles

### ISSUE THREAD

**Issue by rafelafrance** [zooniverse/notes-from-nature-landing#65]
This is happening on all pages but is most obvious on the /completed-expeditions page.

**Comment by mcbouslog** [comment]
@rafelafrance - I think I may have fixed this with the last Bee Flies pull request #84, though possibly not the optimal fix. Please review and let me know what you think.

**Comment by rafelafrance** [comment]
The fix looks good. Closing this issue.
