### ISSUE TITLE
Volunteers still reporting Log In, Field Book issues

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#78]
Please see the thread below.
Mine appears to be working as expected.

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/62303?comment=127481&page=1

**Comment by mcbouslog** [comment]
@denslowm - I can't recreate am.zooni's login issues, and I'm not sure what the best way to proceed is. I could message am.zooni directly, or post a comment in Talk (after your review) that breaks down the typical sign-in process and things to check to confirm properly signed-in? I think the majority of the confusion stems from the fact that notesfromnature.org (landing, field book, etc) and zooniverse.org (classifying, Talk) each independently require login.

**Comment by rafelafrance** [comment]
As of 2017-05-18 I am no longer experiencing this problem on Firefox 53.0.2 64-bit. Ubuntu Linux.

**Comment by denslowm** [comment]
Not sure if this is the same issue (reported this week), but I know that Mark was looking into it as well.

------
if I use the login link on the NfN landing page (bright green with hanging tags background photo) it takes me to https://panoptes.zooniverse.org/users/sign_in; nothing happens when I enter my credentials in Firefox; it does log me in when I use Internet Explorer, although the only function that "sees" me is the Field Book; after using that login, if I go to Talk or Classify, my ID and profile are not shown in the upper right corner and I see "you should sign in" messages. Also if I go to the Zooniverse main site or another Zooniverse project and try to use Talk or Classify, they see me as NOT logged in.

if I use the Zooniverse login - either by starting at the Zooniverse landing page, or by clicking Talk or Classify+a project category on the NfN landing page, and then pressing Sign In on the teal-colored top menu bar - it pops up a window (whose URL I don't know how to identify). If I enter my credential there, it logs me in, shows my ID and photo in the upper right, and NfN sees me as logged in if I use Classify or Talk, but if I click Field Book, it says "Please login to access your Field Book". Also, when I use this login method, if I go to the Zooniverse main site or another Zooniverse project, they see me as already logged in if I use Talk or Classify.

Windows 7 Home Premium Version 6.1 (Build 7601: Service Pack 1)
Firefox 53.0 (32-bit) for Windows

**Comment by mcbouslog** [comment]
I think closed via #346, but please re-open if not.
