### ISSUE TITLE
hashtags in Talk

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#79]
This is really a larger Talk issue (not limited to NFN), so Mark can move it to the appropriate place. 

It is largely summarized here:
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/61853?comment=128262&page=1

The main issue is that a user can't search for a hashtag (e.g., #myhashtag) even though the search box indicates that you can. It is also unclear what is being returned when a user searches with the "#" removed (myhashtag). Is it all boards within a project or just the board that the user in currently in when searching?

**Comment by mcbouslog** [comment]
Issue moved to [zooniverse/Panoptes-Front-End #3442](https://github.com/zooniverse/Panoptes-Front-End/issues/3442) via [**ZenHub**](https://www.zenhub.com/)
