### ISSUE TITLE
Done and Talk in a new tab does not save transcription

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-landing#81]
If you click Done and Talk "in a new tab" is does not save the transcription. Is this the desired behavior? 

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/484/65762?comment=129506&page=1

**Comment by mcbouslog** [comment]
@denslowm - based on am.zooni's follow-up comments, can we close this issue? I think this is related to am.zooni's login issues, not specifically the functionality of Done & Talk?

**Comment by denslowm** [comment]
Yes, thanks.
